# permissions for end users to view drills.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drill-viewer-role
rules:
- apiGroups:
  - apache.goarano.io
  resources:
  - drills
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apache.goarano.io
  resources:
  - drills/status
  verbs:
  - get
