# permissions for end users to edit zookeepers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zookeeper-editor-role
rules:
- apiGroups:
  - apache.goarano.io
  resources:
  - zookeepers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apache.goarano.io
  resources:
  - zookeepers/status
  verbs:
  - get
